name: Android Release Build - React + Ionic

on:
  push:
    tags:
      - 'v*'  

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Node
        uses: actions/setup-node@v4  
        with:
          node-version: 22

      - name: Install Capacitor packages
        run: npm install @capacitor/core @capacitor/android @capacitor/cli --save-dev

      - name: Build React
        run: npm run build

      - name: Add Android platform
        run: npx cap add android

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Give gradlew execute permissions
        run: chmod +x android/gradlew

      - name: Prepare Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > myapp.keystore

      - name: Build Signed APK
        run: |
          npx cap sync android
          cd android
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=../myapp.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4 
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk